CREATE TABLE IF NOT EXISTS resource (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        name VARCHAR(255),
                                        value INTEGER,
                                        money INTEGER,
                                        type VARCHAR(255)
);
