package domain;

public enum Topic {
    PROGRAMMING,UNIVERSITYPROJECT,DOCUMENTATION,
    COOKING,GARDENING, READING,CINEMATOGRAPHY,HISTORY, ART,
    FINANCE, JOURNEYS, SOUSTEINABILITY, FASHION, PERSONALCARE,
    FITNESS, MUSIC, VIDEOGAMES, OTHERS
}
